name: Scalafmt

permissions: read-all

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Code is formatted
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check project is formatted
        uses: jrouly/scalafmt-native-action@v1
        with:
          version: '3.5.9'
